chore(deploy): rename artifact docs

diff --git a/.github/workflows/test-and-deploy.yml b/.github/workflows/test-and-deploy.yml
--- a/.github/workflows/test-and-deploy.yml
+++ b/.github/workflows/test-and-deploy.yml
@@ -55,11 +55,19 @@ jobs:
       - name: Build docs
         run: pnpm docs:build
 
+      - name: Check build output
+        run: |
+          if [ ! -d "./packages/docs/.vitepress/dist" ]; then
+            echo "Build output directory not found"
+            exit 1
+          fi
+
       - name: Upload docs
         uses: actions/upload-artifact@v4
         with:
-          name: docs
+          name: ui-docs
           path: ./packages/docs/.vitepress/dist
+          retention-days: 1
 
   deploy:
     name: Deploy to GitHub Pages
@@ -69,7 +77,7 @@ jobs:
       - name: Download docs
         uses: actions/download-artifact@v4
         with:
-          name: docs
+          name: ui-docs
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
